name: Build Polybot Dev Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build_and_push.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Image
        id: build_and_push
        run: |
          img=${{ secrets.DOCKERHUB_USERNAME }}/polybot-dev:${{ github.run_number }}
          docker build -t $img .
          docker push $img
          echo "image=$img" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    uses: ./.github/workflows/deploy-dev.yaml
    with:

      image: ${{ needs.build.outputs.image }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST_DEV }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}