name: Build Polybot Dev Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build_and_push.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Image
        id: build_and_push
        run: |
          img=aseelarr/polybot-dev:${{ github.run_number }}
          docker build -t $img .
          docker push $img
          echo "image=$img" >> "$GITHUB_OUTPUT"


      - name: Confirm output
        run: |
          echo "Built image: ${{ steps.build_and_push.outputs.image }}"

  deploy:
    needs: build
    uses:  ${{ github.repository }}/.github/workflows/deploy-dev.yaml@dev
    with:

      image: aseelarr/polybot-dev:${{ github.run_number }}

    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST_DEV: ${{ secrets.EC2_HOST_DEV }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      TELEGRAM_BOT_TOKEN_DEV: ${{ secrets.TELEGRAM_BOT_TOKEN_DEV }}
      YOLO_URL_DEV: ${{ secrets.YOLO_URL_DEV }}
      REGION: ${{ secrets.REGION }}
      BUCKET_NAME_DEV: ${{ secrets.BUCKET_NAME_DEV }}