name: Polybot Deploy Dev

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      EC2_HOST:
        required: true
      EC2_USERNAME:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true
      YOLO_URL:
        required: true
      REGION:
        required: true


  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH

        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config <<EOF
          Host ec2
            HostName ${{ secrets.EC2_HOST }}
            User ${{ secrets.EC2_USERNAME }}
            IdentityFile ~/.ssh/private_key
            StrictHostKeyChecking no
          EOF


      - name: Trigger Docker Compose remotely
        env:
          IMG_NAME: ${{ inputs.image }}

          BOT_APP_URL: aseel-dev.fursa.click

        run: |
          ssh ec2 'bash -s' <<EOF
          cd ~/polybot
          git fetch origin
          git reset --hard origin/dev

          cat > .env <<EOL
          IMG_NAME=${{ env.IMG_NAME }}
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          BOT_APP_URL=${{ env.BOT_APP_URL }}
          YOLO_URL=${{ secrets.YOLO_URL }}
          REGION=${{ secrets.REGION }}
          BUCKET_NAME=${{ secrets.BUCKET_NAME }}
          EOL


          docker compose -f docker-compose.dev.yaml pull
          docker compose -f docker-compose.dev.yaml up -d
          
          EOF
