name: Polybot Deploy Prod

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          echo "
          Host ec2
              HostName $EC2_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          " > ~/.ssh/config

      - name: Trigger Compose with Image
        run: |
          ssh ec2 'bash -s' << 'EOF'
            cd ~/polybot
            echo "
            IMG_NAME=${{ inputs.image }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            BOT_APP_URL=your-prod.domain.com
            YOLO_URL=yolo
            REGION=eu-north-1
            BUCKET_NAME=your-bucket
            " > .env

            docker compose -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.prod.yaml up -d
          EOF
