name: Polybot Deploy Dev

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST_DEV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host ec2
              HostName $EC2_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          EOF

      - name: Trigger Docker Compose remotely
        env:
          IMG_NAME: ${{ inputs.image }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_DEV }}
          BOT_APP_URL: aseel-dev.fursa.click
          YOLO_URL: ${{ secrets.YOLO_URL_DEV }}
          REGION: ${{ secrets.REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          ssh ec2 'bash -s' <<EOF
            cd ~/polybot

            cat > .env <<EOL
          IMG_NAME=${IMG_NAME}
          TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
          BOT_APP_URL=${BOT_APP_URL}
          YOLO_URL=${YOLO_URL}
          REGION=${REGION}
          BUCKET_NAME=${BUCKET_NAME}  
          EOL 

            docker compose -f docker-compose.dev.yaml pull
            docker compose -f docker-compose.dev.yaml up -d
          EOF
